Лабораторная работа №7. "Полносвязные нейронные сети (многослойный персептрон). Решение задач регрессии и классификации"

Задание №1.
Решить задачи регрессии и классификации на данных в соответствии с Вашим индивидуальным вариантом (см. Лаб.работы №3, 4), используя полносвязные НС; реализовать НС посредством API Keras и фреймворка TensorFlow; оценить качество полученных моделей с помощью метрик.

Задание №2.
Разработать многослойный персептрон (MLP), с помощью которого можно решать задачи регрессии и классификации. Предусмотреть возможность использования таких функции активации, как sigmoid, tanh и relu; также предусмотреть возможность указать, сколько слоев нужно, сколько на каждом из них нейронов и какую функцию активации должен иметь слой. Реализовать обучение MLP методом обратного распространения ошибки; самостоятельно найти производные функций sigmoid, tanh и relu; реализовать классический градиентный спуск с возможностью указания шага.

# Задание 1

In [1]:
import pandas as pd
data_regression = pd.read_csv("../data/Lab3_Koren_Regression.csv")
data_classification = pd.read_csv("../data/card_transdata.csv")

In [2]:
y_regression = data_regression["Price"]
X_regression = data_regression.drop(columns = ['Price'])
y_classification = data_classification['fraud']
X_classification = data_classification.drop(columns = ['fraud'])

In [3]:
from sklearn.model_selection import train_test_split
X_regression_train, X_regression_test, y_regression_train, y_regression_test = train_test_split(X_regression,
                                                                                                y_regression,
                                                                                                test_size=0.2)
X_classification_train, X_classification_test, y_classification_train, y_classification_test = train_test_split(X_classification,
                                                                                                                y_classification,
                                                                                                                stratify=y_classification,
                                                                                                                test_size=0.2)

In [4]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.metrics import confusion_matrix, classification_report

In [5]:
import tensorflow as tf
import numpy as np

## Регрессия

In [6]:
model_regression = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(934,)),
        tf.keras.layers.Dense(32, activation="linear"),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(1, activation="linear"),
    ]
)

In [7]:
model_regression.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                59840     
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 16)                528       
                                                                 
 dropout_1 (Dropout)         (None, 16)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 62465 (244.00 KB)
Trainable params: 62465 

In [8]:
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="mse")

In [9]:
model_regression.fit(X_regression_train, y_regression_train, epochs=50)

Epoch 1/50
735/735 [==============================] - 2s 867us/step - loss: 27765932.0000
Epoch 2/50
735/735 [==============================] - 1s 830us/step - loss: 22182992.0000
Epoch 3/50
735/735 [==============================] - 1s 832us/step - loss: 21723636.0000
Epoch 4/50
735/735 [==============================] - 1s 825us/step - loss: 22027442.0000
Epoch 5/50
735/735 [==============================] - 1s 829us/step - loss: 21467640.0000
Epoch 6/50
735/735 [==============================] - 1s 830us/step - loss: 21569520.0000
Epoch 7/50
735/735 [==============================] - 1s 830us/step - loss: 21368306.0000
Epoch 8/50
735/735 [==============================] - 1s 837us/step - loss: 21450506.0000
Epoch 9/50
735/735 [==============================] - 1s 859us/step - loss: 21413906.0000
Epoch 10/50
735/735 [==============================] - 1s 839us/step - loss: 21011208.0000
Epoch 11/50
735/735 [==============================] - 1s 834us/step - loss: 21253616.0000
Epoch 12

In [10]:
print(mean_absolute_error(y_regression_test, model_regression.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, model_regression.predict(X_regression_test)))

184/184 [==============================] - 0s 501us/step
3171.9712924009445
184/184 [==============================] - 0s 535us/step
17408816.672156088


## Классификация

In [11]:
model_classification_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(7,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)
model_classification_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="mse")
# verbose=None - не будет логов
model_classification_1.fit(X_classification_train, y_classification_train, epochs=25)

Epoch 1/25
25000/25000 [==============================] - 18s 688us/step - loss: 0.0160
Epoch 2/25
25000/25000 [==============================] - 17s 694us/step - loss: 0.0063
Epoch 3/25
25000/25000 [==============================] - 17s 682us/step - loss: 0.0054
Epoch 4/25
25000/25000 [==============================] - 17s 697us/step - loss: 0.0045
Epoch 5/25
25000/25000 [==============================] - 17s 681us/step - loss: 0.0043
Epoch 6/25
25000/25000 [==============================] - 18s 703us/step - loss: 0.0044
Epoch 7/25
25000/25000 [==============================] - 18s 707us/step - loss: 0.0039
Epoch 8/25
25000/25000 [==============================] - 18s 703us/step - loss: 0.0038
Epoch 9/25
25000/25000 [==============================] - 17s 676us/step - loss: 0.0039
Epoch 10/25
25000/25000 [==============================] - 17s 686us/step - loss: 0.0035
Epoch 11/25
25000/25000 [==============================] - 18s 707us/step - loss: 0.0033
Epoch 12/25
25000/25000 [=====

In [12]:
model_classification_1.predict(X_classification_test, verbose=None)[:5]

array([[0.0000000e+00],
       [4.2081996e-22],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00]], dtype=float32)

In [13]:
y_pred = np.around(model_classification_1.predict(X_classification_test, verbose=None))
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    182519
         1.0       0.99      0.96      0.98     17481

    accuracy                           1.00    200000
   macro avg       0.99      0.98      0.99    200000
weighted avg       1.00      1.00      1.00    200000

[[182304    215]
 [   613  16868]]


In [14]:
w0 = 1 / y_classification_train[y_classification_train==0].shape[0]
w1 = 1 / y_classification_train[y_classification_train==1].shape[0]

In [15]:
model_classification_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(7,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # используем 1 нейрон и sigmoid
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)
model_classification_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="binary_crossentropy")
model_classification_1.fit(X_classification_train, y_classification_train, epochs=25, verbose=None,
                           class_weight={0: w0, 1: w1})
y_pred = np.around(model_classification_1.predict(X_classification_test, verbose=None))
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99    182519
         1.0       0.88      1.00      0.94     17481

    accuracy                           0.99    200000
   macro avg       0.94      0.99      0.96    200000
weighted avg       0.99      0.99      0.99    200000

[[180153   2366]
 [    29  17452]]


In [16]:
model_classification_2 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(7,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # сначала используем 2 нейрона и softmax
        tf.keras.layers.Dense(2, activation="softmax"),
    ]
)

model_classification_2.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="sparse_categorical_crossentropy")
model_classification_2.fit(X_classification_train, y_classification_train, epochs=25,
                           class_weight={0: w0, 1: w1})

Epoch 1/25
25000/25000 [==============================] - 19s 734us/step - loss: 3.5355e-07
Epoch 2/25
25000/25000 [==============================] - 18s 718us/step - loss: 2.2818e-07
Epoch 3/25
25000/25000 [==============================] - 18s 731us/step - loss: 2.0551e-07
Epoch 4/25
25000/25000 [==============================] - 18s 717us/step - loss: 1.8677e-07
Epoch 5/25
25000/25000 [==============================] - 18s 700us/step - loss: 1.8882e-07
Epoch 6/25
25000/25000 [==============================] - 18s 719us/step - loss: 1.5612e-07
Epoch 7/25
25000/25000 [==============================] - 17s 693us/step - loss: 1.4682e-07
Epoch 8/25
25000/25000 [==============================] - 18s 706us/step - loss: 1.2808e-07
Epoch 9/25
25000/25000 [==============================] - 18s 716us/step - loss: 1.3091e-07
Epoch 10/25
25000/25000 [==============================] - 18s 729us/step - loss: 1.2727e-07
Epoch 11/25
25000/25000 [==============================] - 18s 716us/step - los

In [17]:
model_classification_2.predict(X_classification_test, verbose=None)[:5]

array([[9.9999988e-01, 8.8236753e-08],
       [9.9999952e-01, 4.5386872e-07],
       [9.9999964e-01, 3.5827838e-07],
       [9.9999964e-01, 3.5827838e-07],
       [1.0000000e+00, 3.6016301e-09]], dtype=float32)

In [18]:
y_pred = [np.argmax(pred) for pred in model_classification_2.predict(X_classification_test, verbose=None)]

In [19]:
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99    182519
         1.0       0.91      1.00      0.95     17481

    accuracy                           0.99    200000
   macro avg       0.95      0.99      0.97    200000
weighted avg       0.99      0.99      0.99    200000

[[180734   1785]
 [    69  17412]]


In [20]:
model_regression.save('../models/RegressionModel')
model_classification_1.save('../models/ClassificationModel1')
model_classification_2.save('../models/ClassificationModel2')

INFO:tensorflow:Assets written to: ../models/RegressionModel\assets


INFO:tensorflow:Assets written to: ../models/RegressionModel\assets


INFO:tensorflow:Assets written to: ../models/ClassificationModel1\assets


INFO:tensorflow:Assets written to: ../models/ClassificationModel1\assets


INFO:tensorflow:Assets written to: ../models/ClassificationModel2\assets


INFO:tensorflow:Assets written to: ../models/ClassificationModel2\assets


In [21]:
#model_regression_restored = tf.keras.models.load_model('../models/RegressionModel')
#model_regression_restored.summary()

# Задание 2

In [ ]:
import numpy as np

class MLP:
    def __init__(self, layer_sizes, activation_functions):
        self.num_layers = len(layer_sizes)
        self.layer_sizes = layer_sizes
        self.activation_functions = activation_functions
        self.weights = [np.random.randn(layer_sizes[i], layer_sizes[i-1]) for i in range(1, self.num_layers)]
        self.biases = [np.random.randn(layer_sizes[i], 1) for i in range(1, self.num_layers)]

    def _sigmoid(self, x):
        return 1.0 / (1.0 + np.exp(-x))

    def _sigmoid_derivative(self, x):
        return self._sigmoid(x) * (1 - self._sigmoid(x))

    def _tanh(self, x):
        return np.tanh(x)

    def _tanh_derivative(self, x):
        return 1 - np.tanh(x)**2

    def _relu(self, x):
        return np.maximum(0, x)

    def _relu_derivative(self, x):
        return np.where(x > 0, 1, 0)

    def _feed_forward(self, x):
        # х-ый элеменет
        activations = [x]
        zs = []
        for i in range(self.num_layers - 1):
            weight = self.weights[i]
            bias = self.biases[i]
            activation_fn = self.activation_functions[i]
            #умножаем матрицу весов на вектор активаций последнего слоя + вектор смещения
            z = np.dot(weight, activations[-1]) + bias
            zs.append(z)
            if activation_fn == 'sigmoid':
                a = self._sigmoid(z)
            elif activation_fn == 'tanh':
                a = self._tanh(z)
            elif activation_fn == 'relu':
                a = self._relu(z)
            activations.append(a)
        return activations, zs

    def _backpropagate(self, x, y):
        # накопление градиентов функции потерь по весам и смещениям в каждом слое сети
        delta_weights = [np.zeros(weight.shape) for weight in self.weights]
        delta_biases = [np.zeros(bias.shape) for bias in self.biases]
        # прямой проход сети для входных данных x, и сохраняются активации и взвешенные суммы для каждого слоя 
        activations, zs = self._feed_forward(x)
        #разница между предсказанными активациями и фактическими значениями целевой переменной
        delta = (activations[-1] - y) 
        for i in range(self.num_layers - 2, -1, -1):
            # Получение взвешенной суммы
            z = zs[i]
            activation_fn = self.activation_functions[i]
            if activation_fn == 'sigmoid':
                derivative = self._sigmoid_derivative(z)
            elif activation_fn == 'tanh':
                derivative = self._tanh_derivative(z)
            elif activation_fn == 'relu':
                derivative = self._relu_derivative(z)
            #Вычисление градиента по весам для текущего слоя
            delta_weights[i] = np.dot(delta, activations[i].T)
            delta_biases[i] = delta
            delta = np.dot(self.weights[i].T, delta) * derivative
        return delta_weights, delta_biases

    def fit(self, X_train, y_train, learning_rate, num_epochs):
        for epoch in range(num_epochs):
            for x, y in zip(X_train, y_train):
                x = np.array(x, ndmin=2).T
                y = np.array(y, ndmin=2).T
                delta_weights, delta_biases = self._backpropagate(x, y)
                self.weights = [weight - learning_rate * d_weight for weight, d_weight in zip(self.weights, delta_weights)]
                self.biases = [bias - learning_rate * d_bias for bias, d_bias in zip(self.biases, delta_biases)]

    def predict(self, X_test):
        predictions = []
        for x in X_test:
            # массив минимум 2мерный и транспонируем
            x = np.array(x, ndmin=2).T
            activations, _ = self._feed_forward(x)
            predictions.append(activations[-1])
        return predictions

In [ ]:
X_train_regression = np.asarray(X_train_regression, dtype=np.float64)
y_train_regression = np.asarray(y_train_regression, dtype=np.float64).reshape(-1, 1)
# Создание объекта MLP для регрессии
mlp_regression = MLP([13, 1, 1], ['sigmoid', 'sigmoid'])

# Обучаем модель
mlp_regression.fit(X_train_regression, y_train_regression, learning_rate=0.05, num_epochs=10)

X_test_regression = np.asarray(X_test_regression, dtype=np.float64)
# Получаем предсказания модели
predictions_regression = mlp_regression.predict(X_test_regression)

In [ ]:
predictions_regression = np.asarray(predictions_regression, dtype=np.float64).reshape(-1, 1)

In [ ]:
y_test_regression = np.asarray(y_test_regression, dtype=np.float64).reshape(-1, 1)
from sklearn.metrics import r2_score
print(mean_absolute_error(y_test_regression, predictions_regression))
print(mean_squared_error(y_test_regression, predictions_regression))
print(r2_score(y_test_regression, predictions_regression))

In [ ]:
mlp_classifier = MLP([14, 1, 1, 1], ['tanh', 'relu', 'sigmoid'])

mlp_classifier.fit(X_train_classifier, y_train_classifier, learning_rate=0.05, num_epochs=10)

X_test_classifier = np.asarray(X_test_classifier, dtype=np.float64)
# Получаем предсказания модели
predictions_classifier = mlp_classifier.predict(X_test_classifier)

In [ ]:
predictions_classifier=np.asarray(predictions_classifier, dtype=np.float64).reshape(-1, 1)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test_classifier, predictions_classifier[:1253])
print("Accuracy:", accuracy)